# Generated by Django 5.2.14 on 2026-06-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_student_uniq_student_platform_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("military_service", "serviço militar (só homens)"),
                    ("certificate", "comprovante do último ano cursado"),
                    ("transcript", "histórico escolar"),
                    ("conclusion_certificate", "certificado de conclusão (se tiver)"),
                    ("blood_type", "tipo sanguíneo (foto)"),
                    ("address_proof", "comprovante de endereço (foto)"),
                    (
                        "kinship_proof",
                        "comprovante de vínculo (endereço em outro nome)",
                    ),
                    ("id_card", "documento pessoal / RG (foto)"),
                    ("birth_certificate", "certidão de nascimento"),
                    ("marriage_certificate", "certidão de casamento"),
                    ("death_certificate", "certidão de óbito do cônjuge"),
                    ("divorce_decree", "certidão/averbação de divórcio"),
                    ("voter_id", "título de eleitor"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
