# Generated by Django 5.2.14 on 2026-06-20 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biometric", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faceverification",
            name="liveness",
        ),
    ]
