"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environ: toda config sensível vem do backend/.env (ponto único de config).
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# CORS (django-cors-headers) — config no .env (CONVENTION §10: um .env, nada hardcoded).
# Em dev liberamos geral p/ a rede interna acessar fácil; em prod = lista explícita + allow_all False.
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # CORS (cabeçalhos cross-origin p/ os edges/front consumirem o backend)
    "corsheaders",
    # fila async (broker no próprio banco, sem Redis)
    "django_q",
    # integrações externas
    "integrations.finance.asaas.apps.AsaasConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CorsMiddleware o mais alto possível, antes do CommonMiddleware (doc django-cors-headers).
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # dev -> SQLite (default); prod -> PostgreSQL via DATABASE_URL no .env.
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Asaas (integrations.finance.asaas) — config via .env (CONVENTION §8/§10).
# Sem a key o app ainda sobe, mas o system check asaas.E001 erra em vermelho no boot.
# A api-key do Asaas começa com "$" ($aact_...), e o django-environ trata "$" como proxy de
# variável (quebraria o settings). Por isso lemos via os.environ (valor literal) — read_env()
# já populou os.environ acima. Centralizado aqui no settings, ninguém usa os.environ espalhado.
ASAAS_API_KEY = os.environ.get("ASAAS_API_KEY", "")
ASAAS_BASE_URL = env("ASAAS_BASE_URL", default="https://api.asaas.com")
# Webhook-secret (HMAC) e URL externa — usados a partir do 1a-ii/1a-iii. Hex/URL, sem "$".
ASAAS_WEBHOOK_SECRET = env("ASAAS_WEBHOOK_SECRET", default="")
EXTERNAL_URL = env("EXTERNAL_URL", default="")


# Django-Q2 — fila async com broker no próprio banco (sem Redis). `qcluster` roda o worker.
Q_CLUSTER = {
    "name": "mvp",
    "orm": "default",
    "timeout": 90,
    "retry": 120,
}
