"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# django-environ: toda config sensível vem do backend/.env (ponto único de config).
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# CORS (django-cors-headers) — config no .env (CONVENTION §10: um .env, nada hardcoded).
# Em dev liberamos geral p/ a rede interna acessar fácil; em prod = lista explícita + allow_all False.
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # CORS (cabeçalhos cross-origin p/ os edges/front consumirem o backend)
    "corsheaders",
    # fila async (broker no próprio banco, sem Redis)
    "django_q",
    # JWT da API pública (django-ninja-jwt) — RS256 reusa as chaves em keys/ (CONVENTION §10).
    "ninja_jwt",
    # app base do projeto (models base comuns — ex.: fallback logger de eventos sem destino)
    "core.apps.CoreConfig",
    # integrações externas
    "integrations.finance.asaas.apps.AsaasConfig",
    "integrations.finance.infinitepay.apps.InfinitepayConfig",
    "integrations.tools.cep.apps.CepConfig",
    "integrations.tools.cpf.apps.CpfConfig",
    "integrations.ai.apps.AiConfig",
    "integrations.communication.whatsapp.apps.WhatsappConfig",
    "integrations.communication.mail.apps.MailConfig",
    # apps de negócio do monólito
    "notify.apps.NotifyConfig",
    # users = o "quem" (identidade + papéis + dados pessoais). auth/jwt/otp/profiles/roles vivem
    # dentro dele como pacotes; um migration set só (CONVENTION §2). É o AUTH_USER_MODEL.
    "users.apps.UsersConfig",
    # finance = motor de comissão/payout (commissions + payout; fees vem depois). Consome users
    # (FK→User, pix do profile), asaas.payout (PIX-out) e notify. Pasta em inglês (Victor 2026-06-01).
    "finance.apps.FinanceConfig",
    # hub = o POLO (§4 item 5). Hub→Address (FK §4); marca = catálogo no .env. Ações do
    # coordenador entram depois (grupo leadership). Consome users (coordinator/promoter).
    "hub.apps.HubConfig",
]

# User custom (palavra do Victor 2026-06-01; sobrepõe o "User padrão" da CONVENTION §4): a
# identidade carrega o external_id (UUID na borda). Login é passwordless por OTP, então o
# USERNAME_FIELD é o external_id (admin/superuser loga por UUID). Definido ANTES da 1ª migração.
AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CorsMiddleware o mais alto possível, antes do CommonMiddleware (doc django-cors-headers).
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # dev -> SQLite (default); prod -> PostgreSQL via DATABASE_URL no .env.
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media (arquivos servidos) — CONVENTION §6 (Django expõe /media/). Ex.: PNG do QR das cobranças.
# Em dev o Django serve (core/urls.py, DEBUG); em prod é a infra/proxy.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Base LAN do /media/ pra serviços da MESMA sub-rede buscarem o arquivo pelo IP interno (sem TLS/
# DNS/egress) — padrão do legado (`_to_lan`): a Evolution busca o áudio do voice-note (TTS) por
# aqui, não pela URL pública. Vazio => o notify cai no EXTERNAL_URL. Ex. dev: http://10.1.20.30
MEDIA_LAN_BASE = env("MEDIA_LAN_BASE", default="")

# Limite de upload de imagem dos documentos (users/documents) — config, não hardcoded (§10).
MAX_UPLOAD_MB = env.int("MAX_UPLOAD_MB", default=10)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Asaas (integrations.finance.asaas) — config via .env (CONVENTION §8/§10).
# Sem a key o app ainda sobe, mas o system check asaas.E001 erra em vermelho no boot.
# A api-key do Asaas começa com "$" ($aact_...), e o django-environ trata "$" como proxy de
# variável (quebraria o settings). Por isso lemos via os.environ (valor literal) — read_env()
# já populou os.environ acima. Centralizado aqui no settings, ninguém usa os.environ espalhado.
ASAAS_API_KEY = os.environ.get("ASAAS_API_KEY", "")
ASAAS_BASE_URL = env("ASAAS_BASE_URL", default="https://api.asaas.com")
# Token do webhook (= authToken do `asaas-access-token`, NÃO é HMAC — o Asaas não tem HMAC) e URL
# externa, usados a partir do 1a-ii/1a-iii. Hex/URL, sem "$" (lê via env normal). Um token só pros
# dois endpoints que o Asaas chama de volta: webhook de eventos e mecanismo de validação de saque.
ASAAS_WEBHOOK_SECRET = env("ASAAS_WEBHOOK_SECRET", default="")
EXTERNAL_URL = env("EXTERNAL_URL", default="")
# Prazo default (dias) da cobrança PIX quando o caller não passa due_date.
ASAAS_CHARGE_DUE_DAYS = env.int("ASAAS_CHARGE_DUE_DAYS", default=3)
# Onboarding/auto-cadastro do webhook (1a-v): nome do webhook que gerenciamos no Asaas (casamos por
# URL; o nome é só fallback) e TTL (segundos) do nonce de verificação da URL pública.
ASAAS_WEBHOOK_NAME = env("ASAAS_WEBHOOK_NAME", default="dmz-asaas-managed")
URL_VERIFY_NONCE_TTL = env.int("URL_VERIFY_NONCE_TTL", default=600)


# InfinitePay (integrations.finance.infinitepay) — config via .env (CONVENTION §8/§10).
# A InfinitePay NÃO usa api-key: autentica só pelo `handle` (InfiniteTag) — quem recebe é o dono da
# conta, não há segredo no envio. Sem o handle, o system check infinitepay.E001 trava o boot. O handle
# às vezes é colado com "$" à esquerda (InfiniteTag); removemos pra não furar a chamada. Lemos via
# os.environ por simetria com a key do asaas (read_env() já populou os.environ acima).
INFINITEPAY_HANDLE = os.environ.get("INFINITEPAY_HANDLE", "").lstrip("$")
INFINITEPAY_BASE_URL = env("INFINITEPAY_BASE_URL", default="https://api.infinitepay.io")
INFINITEPAY_HTTP_TIMEOUT = env.float("INFINITEPAY_HTTP_TIMEOUT", default=15.0)
# URL de sucesso pós-pagamento (opcional; default = EXTERNAL_URL no serviço de checkout).
INFINITEPAY_REDIRECT_URL = env("INFINITEPAY_REDIRECT_URL", default="")


# ViaCEP (integrations.tools.cep) — lookup de CEP. API pública, sem api-key: só URL e timeout,
# config no .env (CONVENTION §8/§10, nunca hardcoded).
VIACEP_BASE_URL = env("VIACEP_BASE_URL", default="https://viacep.com.br")
VIACEP_TIMEOUT_SECONDS = env.float("VIACEP_TIMEOUT_SECONDS", default=5.0)


# CPFHub (integrations.tools.cpf) — lookup de identidade por CPF (server-side only). §8/§10.
# Tem api-key (header x-api-key). A key é hex (sem "$"), então env() normal serve (a do Asaas
# começa com "$" e exigiu os.environ). Sem a key o check cpf.W001 só AVISA (não trava — tool de apoio).
CPFHUB_API_KEY = env("CPFHUB_API_KEY", default="")
CPFHUB_BASE_URL = env("CPFHUB_BASE_URL", default="https://api.cpfhub.io")
CPFHUB_TIMEOUT = env.float("CPFHUB_TIMEOUT", default=5.0)


# IA (integrations.ai) — engine LLM multi-provider OpenAI-compatible + fallback (CONVENTION §8/§10).
# Todos os providers (deepseek, dashscope, groq, openai, openrouter, nvidia, …) falam o mesmo
# protocolo: cada um precisa só de IA_<NAME>_BASE_URL + IA_<NAME>_API_KEY. Somar um novo é só .env.
# As keys têm chars variados (pontos, hifens) → lemos via os.environ (read_env() já populou acima),
# como no Asaas. IA_FALLBACK_CHAIN="provider:model,..." define a ORDEM de tentativa (1º = default);
# falha rede/timeout/429/5xx cai pro próximo. Config incompleta => check ai.E001/E002/E003 trava o boot.
IA_PROVIDERS = {}
for _ia_name in env.list("IA_PROVIDERS", default=[]):
    _ia_name = _ia_name.strip().lower()
    _ia_base = os.environ.get(f"IA_{_ia_name.upper()}_BASE_URL", "")
    _ia_key = os.environ.get(f"IA_{_ia_name.upper()}_API_KEY", "")
    if _ia_base and _ia_key:
        IA_PROVIDERS[_ia_name] = {"base_url": _ia_base, "api_key": _ia_key}

IA_FALLBACK_CHAIN = []
for _ia_item in env.list("IA_FALLBACK_CHAIN", default=[]):
    if ":" in _ia_item:
        _ia_p, _, _ia_m = _ia_item.partition(":")
        IA_FALLBACK_CHAIN.append((_ia_p.strip(), _ia_m.strip()))

IA_DEFAULT_TEMPERATURE = env.float("IA_DEFAULT_TEMPERATURE", default=0.3)
IA_MAX_TOKENS = env.int("IA_MAX_TOKENS", default=0)
IA_TIMEOUT = env.float("IA_TIMEOUT", default=60.0)

# IA — modalidades de mídia (integrations.ai), via REST httpx. São OPCIONAIS: sem a key o check só
# AVISA (ai.W001/W002/W003), não trava como a cadeia LLM (que é o núcleo). Keys AIza/sk_ (sem "$").
# Gemini = visão (descrever imagem) + geração de imagem; ElevenLabs = TTS; Google Vision = OCR.
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")
GEMINI_BASE_URL = env(
    "GEMINI_BASE_URL", default="https://generativelanguage.googleapis.com/v1beta"
)
GEMINI_VISION_MODEL = env("GEMINI_VISION_MODEL", default="gemini-3-flash-preview")
GEMINI_IMAGE_MODEL = env("GEMINI_IMAGE_MODEL", default="gemini-3.1-flash-image-preview")

ELEVENLABS_API_KEY = env("ELEVENLABS_API_KEY", default="")
ELEVENLABS_BASE_URL = env("ELEVENLABS_BASE_URL", default="https://api.elevenlabs.io")
ELEVENLABS_VOICE_ID = env("ELEVENLABS_VOICE_ID", default="JBFqnCBsd6RMkjVDRZzb")
ELEVENLABS_MODEL_ID = env("ELEVENLABS_MODEL_ID", default="eleven_v3")
ELEVENLABS_OUTPUT_FORMAT = env("ELEVENLABS_OUTPUT_FORMAT", default="mp3_44100_128")
# voice_settings (0.0–1.0; speed 0.25–4.0) — defaults, sobrescrevíveis por request.
ELEVENLABS_STABILITY = env.float("ELEVENLABS_STABILITY", default=0.5)
ELEVENLABS_SIMILARITY_BOOST = env.float("ELEVENLABS_SIMILARITY_BOOST", default=0.75)
ELEVENLABS_SPEED = env.float("ELEVENLABS_SPEED", default=1.0)
ELEVENLABS_STYLE = env.float("ELEVENLABS_STYLE", default=0.0)
ELEVENLABS_SPEAKER_BOOST = env.bool("ELEVENLABS_SPEAKER_BOOST", default=True)
# Voz do TTS por gênero do DESTINATÁRIO — CRUZADO de propósito (regra do Victor): homem recebe voz
# de mulher e vice-versa. Logo ELEVENLABS_VOICE_MALE = a voz que o HOMEM recebe (voice-id feminino)
# e ELEVENLABS_VOICE_FEMALE = a que a MULHER recebe (voice-id masculino). Default = voz padrão
# (não-quebra). NÃO "corrigir" a inversão.
ELEVENLABS_VOICE_FEMALE = env("ELEVENLABS_VOICE_FEMALE", default="JBFqnCBsd6RMkjVDRZzb")
ELEVENLABS_VOICE_MALE = env("ELEVENLABS_VOICE_MALE", default="JBFqnCBsd6RMkjVDRZzb")

GOOGLE_VISION_API_KEY = env("GOOGLE_VISION_API_KEY", default="")
GOOGLE_VISION_BASE_URL = env(
    "GOOGLE_VISION_BASE_URL", default="https://vision.googleapis.com"
)
# Alternativa de auth (prod, mais robusto): path pro JSON do service-account. Vazio => usa a api-key.
GOOGLE_VISION_SERVICE_ACCOUNT_JSON = env(
    "GOOGLE_VISION_SERVICE_ACCOUNT_JSON", default=""
)


# WhatsApp (integrations.communication.whatsapp) — cliente da Evolution API. Config via .env
# (CONVENTION §8/§10). A api-key global é alfanumérica (sem "$"), então env() normal serve. Sem
# base_url/api-key os checks whatsapp.E001/E002 travam o boot.
WHATSAPP_API_BASE_URL = env("WHATSAPP_API_BASE_URL", default="")
WHATSAPP_GLOBAL_API_KEY = env("WHATSAPP_GLOBAL_API_KEY", default="")
WHATSAPP_INSTANCE_NAME = env("WHATSAPP_INSTANCE_NAME", default="default")

# Mail (integrations.communication.mail) — cliente SMTP STARTTLS:587 autenticado. Config via .env
# (CONVENTION §8/§10). A senha do noreply tem "!"/"@" (sem "$"), mas lemos via os.environ literal
# por segurança/simetria com a key do Asaas (read_env() já populou os.environ acima). Sem
# host/user/senha os checks mail.E001/E002/E003 travam o boot.
MAIL_SMTP_HOST = env("MAIL_SMTP_HOST", default="")
MAIL_SMTP_PORT = env.int("MAIL_SMTP_PORT", default=587)
MAIL_SMTP_USER = env("MAIL_SMTP_USER", default="")
MAIL_SMTP_PASSWORD = os.environ.get("MAIL_SMTP_PASSWORD", "")
MAIL_FROM_EMAIL = env("MAIL_FROM_EMAIL", default="") or MAIL_SMTP_USER
MAIL_FROM_NAME = env("MAIL_FROM_NAME", default="Supletivo Brasil")
MAIL_TIMEOUT = env.int("MAIL_TIMEOUT", default=30)


# Django-Q2 — fila async com broker no próprio banco (sem Redis). `qcluster` roda o worker.
Q_CLUSTER = {
    "name": "mvp",
    "orm": "default",
    "timeout": 90,
    "retry": 120,
}


# users — auth (jwt, otp) · profiles · roles (CONVENTION §2/§4/§9). Config via .env (§10).
# ── JWT (users.auth.jwt): RS256, par de chaves PEM. As chaves são geradas no 1º uso se faltarem
# (users/auth/jwt/keys.py) num diretório gitignored — a privada NUNCA vai pro git. Paths relativos
# ao BASE_DIR. issuer/audience e expirações são config (defaults = porte do legado).
JWT_PRIVATE_KEY_PATH = BASE_DIR / env(
    "JWT_PRIVATE_KEY_PATH", default="keys/jwt_private.pem"
)
JWT_PUBLIC_KEY_PATH = BASE_DIR / env(
    "JWT_PUBLIC_KEY_PATH", default="keys/jwt_public.pem"
)
JWT_ALGORITHM = env("JWT_ALGORITHM", default="RS256")
JWT_ACCESS_EXPIRE_MINUTES = env.int("JWT_ACCESS_EXPIRE_MINUTES", default=30)
JWT_REFRESH_EXPIRE_MINUTES = env.int("JWT_REFRESH_EXPIRE_MINUTES", default=1440)
JWT_ISSUER = env("JWT_ISSUER", default="supletivo")
JWT_AUDIENCE = env("JWT_AUDIENCE", default="")

# django-ninja-jwt (substitui o JWT escrito à mão — Victor 2026-06-02). RS256 REUSA o mesmo par
# PEM em keys/ (lido path-based porque o objeto `settings` ainda está sendo montado aqui). Sem
# consumidor externo de JWKS → o endpoint JWKS foi removido. issue/decode em users/auth/jwt/service.
from users.auth.jwt import keys as _jwt_keys  # noqa: E402 (import tardio: precisa dos paths acima)

_JWT_PRIVATE_PEM, _JWT_PUBLIC_PEM = _jwt_keys.read_or_create_pair(
    JWT_PRIVATE_KEY_PATH, JWT_PUBLIC_KEY_PATH
)
NINJA_JWT = {
    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": _JWT_PRIVATE_PEM,
    "VERIFYING_KEY": _JWT_PUBLIC_PEM,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_EXPIRE_MINUTES),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=JWT_REFRESH_EXPIRE_MINUTES),
    "ISSUER": JWT_ISSUER or None,
    "AUDIENCE": JWT_AUDIENCE or None,
}

# ── OTP (users.auth.otp): código numérico, hash SHA256 (plaintext nunca persiste), TTL/tentativas
# e rate-limit em DB (sem Redis — Django-Q usa o banco). Defaults = porte do legado.
OTP_TTL_S = env.int("OTP_TTL_S", default=300)
OTP_NUM_DIGITS = env.int("OTP_NUM_DIGITS", default=6)
OTP_MAX_ATTEMPTS = env.int("OTP_MAX_ATTEMPTS", default=3)
OTP_RATELIMIT_WINDOW_S = env.int("OTP_RATELIMIT_WINDOW_S", default=30)
OTP_RATELIMIT_HOURLY_MAX = env.int("OTP_RATELIMIT_HOURLY_MAX", default=5)
OTP_FOOTER = env("OTP_FOOTER", default="")
OTP_ACTIVE = env.bool("OTP_ACTIVE", default=True)

# ── ROLES (users.roles): catálogo de transições no .env, NÃO em DB (§9). JSON: lista de
# {from_role, to_role, mode: add|replace, requires_role?, forbids_role?, blocking?}. A tabela
# users.UserRole guarda só quem tem qual role agora + histórico. Default = cadeia confirmada
# pelo Victor (com training: candidate→training→promoter). Catálogo inválido derruba o boot.
ROLE_RULES = env.json(
    "ROLE_RULES",
    default=[
        {"from_role": None, "to_role": "lead", "mode": "add"},
        {"from_role": "lead", "to_role": "enrollment", "mode": "replace"},
        {"from_role": "enrollment", "to_role": "student", "mode": "replace"},
        {
            "from_role": None,
            "to_role": "veteran",
            "mode": "add",
            "requires_role": "student",
        },
        {"from_role": None, "to_role": "candidate", "mode": "add"},
        {"from_role": "candidate", "to_role": "training", "mode": "replace"},
        {"from_role": "training", "to_role": "promoter", "mode": "replace"},
        {
            "from_role": None,
            "to_role": "coordinator",
            "mode": "add",
            "requires_role": "promoter",
        },
    ],
)

# finance (app finance) — motor de comissão/payout. Valores em REAIS (string→Decimal no finance.config,
# nunca float; só o infinitepay usa centavos). DEV mini de propósito: teste mexe DINHEIRO REAL →
# comissão 1 / bônus 5 / coord 1 / threshold 5. PROD pede ao Victor (ref 100/500/50). §8/§10.
COMMISSION_DIRECT = env("COMMISSION_DIRECT", default="1")
COMMISSION_BONUS_FLAT = env("COMMISSION_BONUS_FLAT", default="5")
COMMISSION_COORDINATOR = env("COMMISSION_COORDINATOR", default="1")
COMMISSION_BONUS_THRESHOLD = env.int("COMMISSION_BONUS_THRESHOLD", default=5)
# fechamento: dia (0=seg..4=sex) e hora em America/Sao_Paulo. O Schedule é WEEKLY (sem croniter).
COMMISSION_CLOSING_WEEKDAY = env.int("COMMISSION_CLOSING_WEEKDAY", default=4)
COMMISSION_CLOSING_HOUR = env.int("COMMISSION_CLOSING_HOUR", default=18)

# matrícula (funil do aluno, §4 itens 11/13) — preço por gateway (Victor 2026-06-04): cartão R$1 /
# PIX R$5 (mínimo do Asaas). Reais (Decimal no lead/config; infinitepay converte p/ centavos). PROD =
# pedir ao Victor (§8). Descrição da cobrança = config (não fixa no código).
ENROLLMENT_PRICE_CARD = env("ENROLLMENT_PRICE_CARD", default="1")
ENROLLMENT_PRICE_PIX = env("ENROLLMENT_PRICE_PIX", default="5")
ENROLLMENT_DESCRIPTION = env("ENROLLMENT_DESCRIPTION", default="Matrícula Supletivo")

# treino (LMS do funil do colaborador, §4 item 7) — nota de corte (0–10) p/ aprovar uma submissão da IA.
# Default 6 (palavra do dono). PROD = pedir ao Victor se mudar.
TRAINING_PASS_SCORE = env("TRAINING_PASS_SCORE", default="6")


# hub (app hub) — o POLO (§4 item 5). Marca = catálogo no .env (HUB_BRANDS), igual às roles (§9):
# validado no hub/interface, NÃO choices fixo no model. `ieadpg`→`standard` (Victor 2026-06-03).
HUB_BRANDS = env.list("HUB_BRANDS", default=["wyden", "estacio", "standard"])
DEFAULT_HUB_BRAND = env("DEFAULT_HUB_BRAND", default="standard")
# conta-mãe (seed_defaults): no início TUDO centralizado no Victor — staff (superuser) + promoter +
# coordinator do hub padrão, na MESMA conta (Victor 2026-06-03). A senha é só p/ o /admin (a API loga
# por OTP). DEV = placeholders; PROD = dados REAIS do Victor (cpf/phone só dígitos). Senha via os.environ
# (pode ter char especial), simetria com asaas/mail.
DEFAULT_STAFF_CPF = env("DEFAULT_STAFF_CPF", default="")
DEFAULT_STAFF_PHONE = env("DEFAULT_STAFF_PHONE", default="")
DEFAULT_STAFF_NAME = env("DEFAULT_STAFF_NAME", default="Staff")
DEFAULT_STAFF_PASSWORD = os.environ.get("DEFAULT_STAFF_PASSWORD", "")
